defaults: &defaults
  docker:
    - image: circleci/node:10.15.1-browsers
  working_directory: &root ~/physics

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: &dep_cache_key dependency-cache-{{ checksum "package.json" }}-{{ checksum "packages/physics-jumpy/package.json" }}-{{ checksum "packages/physics-projectile/package.json" }}
      - run:
          name: Installing dependencies with `npm install`
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/physics/.npmrc
            npm install
      - run:
          name: Bootstrapping Lerna
          command: npm run bootstrap
      - save_cache:
          key: *dep_cache_key
          paths:
            - node_modules
            - packages/physics-jumpy/node_modules
            - packages/physics-projectile/node_modules
      - persist_to_workspace:
          root: *root
          paths:
            - .npmrc
            - packages/*/dist

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: *dep_cache_key
      - attach_workspace:
          at: *root
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:coverage

  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: *dep_cache_key
      - attach_workspace:
          at: *root
      - run:
          name: Publish
          command: npm run publish

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
